const AllProducts= [
    {"id": 1, "name": "Organic Apples", "image": "https://example.com/organic-apples.jpg", "price": 3.99, "details": "Crisp and juicy organic apples."},
    {"id": 2, "name": "Organic Carrots", "image": "https://example.com/organic-carrots.jpg", "price": 1.99, "details": "Sweet and crunchy organic carrots."},
    {"id": 3, "name": "Organic Tomatoes", "image": "https://example.com/organic-tomatoes.jpg", "price": 2.99, "details": "Fresh organic tomatoes."},
    {"id": 4, "name": "Organic Bananas", "image": "https://example.com/organic-bananas.jpg", "price": 1.29, "details": "Ripe organic bananas."},
    {"id": 5, "name": "Organic Spinach", "image": "https://example.com/organic-spinach.jpg", "price": 2.49, "details": "Nutritious organic spinach."},
    {"id": 6, "name": "Organic Blueberries", "image": "https://example.com/organic-blueberries.jpg", "price": 4.99, "details": "Juicy organic blueberries."},
    {"id": 7, "name": "Organic Broccoli", "image": "https://example.com/organic-broccoli.jpg", "price": 2.99, "details": "Fresh organic broccoli florets."},
    {"id": 8, "name": "Organic Bell Peppers", "image": "https://example.com/organic-bell-peppers.jpg", "price": 3.49, "details": "Sweet organic bell peppers."},
    {"id": 9, "name": "Organic Lemons", "image": "https://example.com/organic-lemons.jpg", "price": 3.49, "details": "Tangy organic lemons."},
    {"id": 10, "name": "Organic Cucumbers", "image": "https://example.com/organic-cucumbers.jpg", "price": 1.99, "details": "Crisp organic cucumbers."},
    {"id": 11, "name": "Organic Kale", "image": "https://example.com/organic-kale.jpg", "price": 2.79, "details": "Healthy organic kale leaves."},
    {"id": 12, "name": "Organic Strawberries", "image": "https://example.com/organic-strawberries.jpg", "price": 5.99, "details": "Sweet organic strawberries."},
    {"id": 13, "name": "Organic Sweet Potatoes", "image": "https://example.com/organic-sweet-potatoes.jpg", "price": 3.49, "details": "Nutritious organic sweet potatoes."},
    {"id": 14, "name": "Organic Onions", "image": "https://example.com/organic-onions.jpg", "price": 2.49, "details": "Flavorful organic onions."},
    {"id": 15, "name": "Organic Garlic", "image": "https://example.com/organic-garlic.jpg", "price": 2.99, "details": "Strong organic garlic cloves."},
    {"id": 16, "name": "Organic Peaches", "image": "https://example.com/organic-peaches.jpg", "price": 4.99, "details": "Juicy organic peaches."},
    {"id": 17, "name": "Organic Avocados", "image": "https://example.com/organic-avocados.jpg", "price": 2.99, "details": "Creamy organic avocados."},
    {"id": 18, "name": "Organic Zucchini", "image": "https://example.com/organic-zucchini.jpg", "price": 2.49, "details": "Fresh organic zucchini."},
    {"id": 19, "name": "Organic Grapes", "image": "https://example.com/organic-grapes.jpg", "price": 3.99, "details": "Sweet organic grapes."},
    {"id": 20, "name": "Organic Raspberries", "image": "https://example.com/organic-raspberries.jpg", "price": 5.99, "details": "Tangy organic raspberries."},
    {"id": 21, "name": "Organic Celery", "image": "https://example.com/organic-celery.jpg", "price": 1.99, "details": "Crisp organic celery stalks."},
    {"id": 22, "name": "Organic Cabbage", "image": "https://example.com/organic-cabbage.jpg", "price": 2.49, "details": "Fresh organic cabbage."},
    {"id": 23, "name": "Organic Pears", "image": "https://example.com/organic-pears.jpg", "price": 3.49, "details": "Juicy organic pears."},
    {"id": 24, "name": "Organic Beets", "image": "https://example.com/organic-beets.jpg", "price": 2.99, "details": "Earthy organic beets."},
    {"id": 25, "name": "Organic Plums", "image": "https://example.com/organic-plums.jpg", "price": 4.49, "details": "Sweet organic plums."},
    {"id": 26, "name": "Organic Asparagus", "image": "https://example.com/organic-asparagus.jpg", "price": 3.99, "details": "Tender organic asparagus spears."},
    {"id": 27, "name": "Organic Limes", "image": "https://example.com/organic-limes.jpg", "price": 3.49, "details": "Zesty organic limes."},
    {"id": 28, "name": "Organic Brussels Sprouts", "image": "https://example.com/organic-brussels-sprouts.jpg", "price": 3.49, "details": "Fresh organic Brussels sprouts."},
    {"id": 29, "name": "Organic Radishes", "image": "https://example.com/organic-radishes.jpg", "price": 1.99, "details": "Crunchy organic radishes."},
    {"id": 30, "name": "Organic Cherries", "image": "https://example.com/organic-cherries.jpg", "price": 6.99, "details": "Sweet and tart organic cherries."},
    {"id": 31, "name": "Organic Whole Milk", "image": "https://example.com/whole-milk.jpg", "price": 4.49, "details": "Organic whole milk with full cream."},
    {"id": 32, "name": "Greek Yogurt", "image": "https://example.com/greek-yogurt.jpg", "price": 2.79, "details": "Thick Greek yogurt with probiotics."},
    {"id": 33, "name": "Grade A Large Eggs", "image": "https://example.com/eggs.jpg", "price": 2.99, "details": "Large, fresh eggs from pasture-raised chickens."},
    {"id": 34, "name": "Organic Skim Milk", "image": "https://example.com/skim-milk.jpg", "price": 4.29, "details": "Low-fat organic skim milk."},
    {"id": 35, "name": "Cheddar Cheese", "image": "https://example.com/cheddar-cheese.jpg", "price": 5.49, "details": "Aged cheddar cheese with a sharp flavor."},
    {"id": 36, "name": "Mozzarella Cheese", "image": "https://example.com/mozzarella-cheese.jpg", "price": 4.99, "details": "Fresh mozzarella cheese for pizzas and salads."},
    {"id": 37, "name": "Butter", "image": "https://example.com/butter.jpg", "price": 3.99, "details": "Creamy butter made from organic cream."},
    {"id": 38, "name": "Cottage Cheese", "image": "https://example.com/cottage-cheese.jpg", "price": 2.99, "details": "Low-fat cottage cheese with a mild flavor."},
    {"id": 39, "name": "Greek Yogurt with Honey", "image": "https://example.com/greek-yogurt-honey.jpg", "price": 3.49, "details": "Greek yogurt sweetened with honey."},
    {"id": 40, "name": "Organic Sour Cream", "image": "https://example.com/sour-cream.jpg", "price": 3.29, "details": "Creamy organic sour cream."},
    {"id": 41, "name": "Organic Cream Cheese", "image": "https://example.com/cream-cheese.jpg", "price": 3.99, "details": "Smooth organic cream cheese."},
    {"id": 42, "name": "Goat Cheese", "image": "https://example.com/goat-cheese.jpg", "price": 5.99, "details": "Tangy and creamy goat cheese."},
    {"id": 43, "name": "Ricotta Cheese", "image": "https://example.com/ricotta-cheese.jpg", "price": 4.49, "details": "Light and fluffy ricotta cheese."},
    {"id": 44, "name": "Almond Milk", "image": "https://example.com/almond-milk.jpg", "price": 3.49, "details": "Creamy almond milk with a nutty flavor."},
    {"id": 45, "name": "Soy Milk", "image": "https://example.com/soy-milk.jpg", "price": 3.29, "details": "Rich and smooth soy milk."},
    {"id": 46, "name": "Organic Egg Whites", "image": "https://example.com/egg-whites.jpg", "price": 4.49, "details": "Pasteurized organic egg whites."},
    {"id": 47, "name": "Parmesan Cheese", "image": "https://example.com/parmesan-cheese.jpg", "price": 6.99, "details": "Aged Parmesan cheese with a strong flavor."},
    {"id": 48, "name": "Organic Kefir", "image": "https://example.com/kefir.jpg", "price": 4.99, "details": "Fermented organic kefir for digestive health."},
    {"id": 49, "name": "Vanilla Yogurt", "image": "https://example.com/vanilla-yogurt.jpg", "price": 2.79, "details": "Creamy vanilla yogurt with a hint of sweetness."},
    {"id": 50, "name": "Organic Heavy Cream", "image": "https://example.com/heavy-cream.jpg", "price": 5.99, "details": "Rich organic heavy cream for cooking and baking."},
    {"id": 51, "name": "Organic Low-Fat Milk", "image": "https://example.com/low-fat-milk.jpg", "price": 4.29, "details": "Organic low-fat milk with reduced fat content."},
    {"id": 52, "name": "Organic Edamame", "image": "https://example.com/edamame.jpg", "price": 3.49, "details": "Protein-rich organic edamame."},
    {"id": 53, "name": "Organic Chevre", "image": "https://example.com/chevre.jpg", "price": 6.49, "details": "Soft and spreadable organic chevre cheese."},
    {"id": 54, "name": "Organic Feta Cheese", "image": "https://example.com/feta-cheese.jpg", "price": 5.99, "details": "Tangy organic feta cheese."},
    {"id": 55, "name": "Organic Whipping Cream", "image": "https://example.com/whipping-cream.jpg", "price": 6.49, "details": "Organic whipping cream for desserts."},
    {"id": 56, "name": "Organic Ice Cream", "image": "https://example.com/ice-cream.jpg", "price": 7.49, "details": "Delicious organic ice cream in various flavors."},
    {"id": 57, "name": "Organic Yogurt Drink", "image": "https://example.com/yogurt-drink.jpg", "price": 3.49, "details": "Probiotic-rich organic yogurt drink."},
    {"id": 58, "name": "Organic Cream Cheese Spread", "image": "https://example.com/cream-cheese-spread.jpg", "price": 4.29, "details": "Smooth organic cream cheese spread."},
    {"id": 59, "name": "Organic Ricotta Cheese", "image": "https://example.com/organic-ricotta-cheese.jpg", "price": 4.99, "details": "Light organic ricotta cheese."},
    {"id": 60, "name": "Organic Gouda Cheese", "image": "https://example.com/gouda-cheese.jpg", "price": 6.99, "details": "Aged organic Gouda cheese with a rich flavor."},
    {"id": 61, "name": "Grass-Fed Ground Beef", "image": "https://example.com/ground-beef.jpg", "price": 7.99, "details": "Lean grass-fed ground beef."},
    {"id": 62, "name": "Wild-Caught Salmon Fillets", "image": "https://example.com/salmon-fillets.jpg", "price": 10.99, "details": "Fresh wild-caught salmon fillets."},
    {"id": 63, "name": "Cage-Free Chicken Breasts", "image": "https://example.com/chicken-breasts.jpg", "price": 6.99, "details": "Tender cage-free chicken breasts."},
    {"id": 64, "name": "Organic Pork Chops", "image": "https://example.com/pork-chops.jpg", "price": 8.99, "details": "Juicy organic pork chops."},
    {"id": 65, "name": "Free-Range Turkey", "image": "https://example.com/turkey.jpg", "price": 12.99, "details": "Tender free-range turkey breast."},
    {"id": 66, "name": "Beef Sirloin Steaks", "image": "https://example.com/sirloin-steaks.jpg", "price": 9.99, "details": "Premium beef sirloin steaks."},
    {"id": 67, "name": "Organic Chicken Thighs", "image": "https://example.com/chicken-thighs.jpg", "price": 5.99, "details": "Flavorful organic chicken thighs."},
    {"id": 68, "name": "Wild-Caught Shrimp", "image": "https://example.com/shrimp.jpg", "price": 11.99, "details": "Sweet wild-caught shrimp."},
    {"id": 69, "name": "Organic Lamb Chops", "image": "https://example.com/lamb-chops.jpg", "price": 14.99, "details": "Tender organic lamb chops."},
    {"id": 70, "name": "Grass-Fed Beef Roast", "image": "https://example.com/beef-roast.jpg", "price": 13.99, "details": "Hearty grass-fed beef roast."},
    {"id": 71, "name": "Organic Chicken Wings", "image": "https://example.com/chicken-wings.jpg", "price": 7.49, "details": "Delicious organic chicken wings."},
    {"id": 72, "name": "Wild-Caught Cod", "image": "https://example.com/cod.jpg", "price": 9.49, "details": "Mild wild-caught cod fillets."},
    {"id": 73, "name": "Organic Beef Kebabs", "image": "https://example.com/beef-kebabs.jpg", "price": 11.49, "details": "Marinated organic beef kebabs."},
    {"id": 74, "name": "Cage-Free Duck Breast", "image": "https://example.com/duck-breast.jpg", "price": 15.99, "details": "Rich and flavorful cage-free duck breast."},
    {"id": 75, "name": "Organic Salmon Burgers", "image": "https://example.com/salmon-burgers.jpg", "price": 8.99, "details": "Tasty organic salmon burgers."},
    {"id": 76, "name": "Free-Range Chicken Sausages", "image": "https://example.com/chicken-sausages.jpg", "price": 6.49, "details": "Flavorful free-range chicken sausages."},
    {"id": 77, "name": "Grass-Fed Beef Liver", "image": "https://example.com/beef-liver.jpg", "price": 4.99, "details": "Nutritious grass-fed beef liver."},
    {"id": 78, "name": "Organic Crab Meat", "image": "https://example.com/crab-meat.jpg", "price": 12.99, "details": "Sweet organic crab meat."},
    {"id": 79, "name": "Wild-Caught Tuna Steaks", "image": "https://example.com/tuna-steaks.jpg", "price": 13.49, "details": "Fresh wild-caught tuna steaks."},
    {"id": 80, "name": "Organic Beef Short Ribs", "image": "https://example.com/beef-short-ribs.jpg", "price": 14.49, "details": "Tender organic beef short ribs."},
    {"id": 81, "name": "Free-Range Chicken Drumsticks", "image": "https://example.com/chicken-drumsticks.jpg", "price": 5.49, "details": "Juicy free-range chicken drumsticks."},
    {"id": 82, "name": "Grass-Fed Beef Filet Mignon", "image": "https://example.com/filet-mignon.jpg", "price": 19.99, "details": "Premium grass-fed beef filet mignon."},
    {"id": 83, "name": "Organic Tilapia Fillets", "image": "https://example.com/tilapia-fillets.jpg", "price": 7.99, "details": "Mild organic tilapia fillets."},
    {"id": 84, "name": "Wild-Caught Scallops", "image": "https://example.com/scallops.jpg", "price": 15.49, "details": "Tender wild-caught scallops."},
    {"id": 85, "name": "Organic Beef Brisket", "image": "https://example.com/beef-brisket.jpg", "price": 11.99, "details": "Flavorful organic beef brisket."},
    {"id": 86, "name": "Cage-Free Quail", "image": "https://example.com/quail.jpg", "price": 16.99, "details": "Delicate cage-free quail meat."},
    {"id": 87, "name": "Grass-Fed Beef Chuck Roast", "image": "https://example.com/beef-chuck-roast.jpg", "price": 12.99, "details": "Hearty grass-fed beef chuck roast."},
    {"id": 88, "name": "Organic Swordfish Steaks", "image": "https://example.com/swordfish-steaks.jpg", "price": 14.49, "details": "Rich and meaty organic swordfish steaks."},
    {"id": 89, "name": "Free-Range Turkey Sausages", "image": "https://example.com/turkey-sausages.jpg", "price": 6.99, "details": "Lean free-range turkey sausages."},
    {"id": 90, "name": "Wild-Caught Mahi Mahi", "image": "https://example.com/mahi-mahi.jpg", "price": 9.99, "details": "Flaky wild-caught mahi mahi fillets."},
    {"id": 91, "name": "Organic Apple Juice", "image": "https://example.com/apple-juice.jpg", "price": 3.49, "details": "Pure organic apple juice."},
    {"id": 92, "name": "Almond Milk", "image": "https://example.com/almond-milk.jpg", "price": 3.49, "details": "Creamy almond milk with a nutty flavor."},
    {"id": 93, "name": "Green Tea", "image": "https://example.com/green-tea.jpg", "price": 4.99, "details": "Refreshing green tea with antioxidants."},
    {"id": 94, "name": "Sparkling Water", "image": "https://example.com/sparkling-water.jpg", "price": 2.99, "details": "Carbonated sparkling water with a hint of flavor."},
    {"id": 95, "name": "Organic Coffee", "image": "https://example.com/organic-coffee.jpg", "price": 7.99, "details": "Rich organic coffee beans."},
    {"id": 96, "name": "Coconut Water", "image": "https://example.com/coconut-water.jpg", "price": 3.99, "details": "Hydrating coconut water."},
    {"id": 97, "name": "Orange Juice", "image": "https://example.com/orange-juice.jpg", "price": 4.29, "details": "Freshly squeezed orange juice."},
    {"id": 98, "name": "Herbal Tea", "image": "https://example.com/herbal-tea.jpg", "price": 4.49, "details": "Soothing herbal tea with natural flavors."},
    {"id": 99, "name": "Organic Lemonade", "image": "https://example.com/organic-lemonade.jpg", "price": 3.79, "details": "Refreshing organic lemonade."},
    {"id": 100, "name": "Protein Shake", "image": "https://example.com/protein-shake.jpg", "price": 5.99, "details": "Nutritious protein shake with essential vitamins."},
    {"id": 101, "name": "Cold Brew Coffee", "image": "https://example.com/cold-brew-coffee.jpg", "price": 6.49, "details": "Smooth cold brew coffee concentrate."},
    {"id": 102, "name": "Ginger Ale", "image": "https://example.com/ginger-ale.jpg", "price": 3.29, "details": "Spicy and sweet ginger ale."},
    {"id": 103, "name": "Fruit Smoothie", "image": "https://example.com/fruit-smoothie.jpg", "price": 4.99, "details": "Blended fruit smoothie with various flavors."},
    {"id": 104, "name": "Kombucha", "image": "https://example.com/kombucha.jpg", "price": 4.79, "details": "Fermented kombucha tea with probiotics."},
    {"id": 105, "name": "Iced Tea", "image": "https://example.com/iced-tea.jpg", "price": 3.49, "details": "Chilled iced tea with a hint of lemon."},
    {"id": 106, "name": "Cranberry Juice", "image": "https://example.com/cranberry-juice.jpg", "price": 3.99, "details": "Tart cranberry juice with vitamin C."},
    {"id": 107, "name": "Red Wine", "image": "https://example.com/red-wine.jpg", "price": 12.99, "details": "Smooth red wine with a full body."},
    {"id": 108, "name": "White Wine", "image": "https://example.com/white-wine.jpg", "price": 11.99, "details": "Crisp white wine with fruity notes."},
    {"id": 109, "name": "Apple Cider", "image": "https://example.com/apple-cider.jpg", "price": 4.49, "details": "Spiced apple cider for a warm treat."},
    {"id": 110, "name": "Herbal Infusion", "image": "https://example.com/herbal-infusion.jpg", "price": 4.29, "details": "A blend of herbal infusions for relaxation."},
    {"id": 111, "name": "Matcha Tea", "image": "https://example.com/matcha-tea.jpg", "price": 5.49, "details": "Rich matcha tea with antioxidants."},
    {"id": 112, "name": "Sparkling Lemonade", "image": "https://example.com/sparkling-lemonade.jpg", "price": 3.79, "details": "Sparkling lemonade with a citrus twist."},
    {"id": 113, "name": "Raspberry Juice", "image": "https://example.com/raspberry-juice.jpg", "price": 4.29, "details": "Sweet and tart raspberry juice."},
    {"id": 114, "name": "Organic Soy Milk", "image": "https://example.com/soy-milk.jpg", "price": 3.29, "details": "Smooth organic soy milk."},
    {"id": 115, "name": "Peach Tea", "image": "https://example.com/peach-tea.jpg", "price": 4.49, "details": "Sweet and fruity peach tea."},
    {"id": 116, "name": "Energy Drink", "image": "https://example.com/energy-drink.jpg", "price": 2.99, "details": "Energy drink with vitamins and caffeine."},
    {"id": 117, "name": "Mint Lemonade", "image": "https://example.com/mint-lemonade.jpg", "price": 3.79, "details": "Refreshing lemonade with mint."},
    {"id": 118, "name": "Organic Tomato Juice", "image": "https://example.com/tomato-juice.jpg", "price": 3.99, "details": "Rich organic tomato juice."},
    {"id": 119, "name": "Coconut Milk", "image": "https://example.com/coconut-milk.jpg", "price": 4.29, "details": "Creamy coconut milk for cooking and baking."},
    {"id": 120, "name": "Tropical Juice Blend", "image": "https://example.com/tropical-juice-blend.jpg", "price": 4.79, "details": "Exotic tropical juice blend."},
    {"id": 121, "name": "Whole Wheat Bread", "image": "https://example.com/whole-wheat-bread.jpg", "price": 3.49, "details": "Nutritious whole wheat bread."},
    {"id": 122, "name": "Sourdough Bread", "image": "https://example.com/sourdough-bread.jpg", "price": 4.99, "details": "Tangy sourdough bread."},
    {"id": 123, "name": "Organic Bagels", "image": "https://example.com/organic-bagels.jpg", "price": 5.49, "details": "Delicious organic bagels in various flavors."},
    {"id": 124, "name": "Croissants", "image": "https://example.com/croissants.jpg", "price": 3.99, "details": "Flaky and buttery croissants."},
    {"id": 125, "name": "Cinnamon Rolls", "image": "https://example.com/cinnamon-rolls.jpg", "price": 4.29, "details": "Sweet cinnamon rolls with icing."},
    {"id": 126, "name": "Organic Whole Grain Bread", "image": "https://example.com/whole-grain-bread.jpg", "price": 3.99, "details": "Hearty organic whole grain bread."},
    {"id": 127, "name": "Raisin Bread", "image": "https://example.com/raisin-bread.jpg", "price": 4.49, "details": "Sweet and fruity raisin bread."},
    {"id": 128, "name": "Organic English Muffins", "image": "https://example.com/english-muffins.jpg", "price": 4.29, "details": "Organic English muffins for breakfast."},
    {"id": 129, "name": "Brioche", "image": "https://example.com/brioche.jpg", "price": 5.99, "details": "Soft and sweet brioche bread."},
    {"id": 130, "name": "Chocolate Cake", "image": "https://example.com/chocolate-cake.jpg", "price": 6.49, "details": "Rich and decadent chocolate cake."},
    {"id": 131, "name": "Lemon Pound Cake", "image": "https://example.com/lemon-pound-cake.jpg", "price": 5.49, "details": "Moist lemon pound cake with a zesty flavor."},
    {"id": 132, "name": "Organic Donuts", "image": "https://example.com/organic-donuts.jpg", "price": 4.99, "details": "Fresh organic donuts in assorted flavors."},
    {"id": 133, "name": "Apple Pie", "image": "https://example.com/apple-pie.jpg", "price": 7.99, "details": "Classic apple pie with a buttery crust."},
    {"id": 134, "name": "Pumpkin Bread", "image": "https://example.com/pumpkin-bread.jpg", "price": 4.99, "details": "Spiced pumpkin bread perfect for fall."},
    {"id": 135, "name": "Pecan Pie", "image": "https://example.com/pecan-pie.jpg", "price": 6.99, "details": "Sweet and nutty pecan pie."},
    {"id": 136, "name": "Organic Multigrain Bread", "image": "https://example.com/multigrain-bread.jpg", "price": 4.29, "details": "Healthy organic multigrain bread."},
    {"id": 137, "name": "Gingerbread Cookies", "image": "https://example.com/gingerbread-cookies.jpg", "price": 3.99, "details": "Spicy gingerbread cookies with a festive touch."},
    {"id": 138, "name": "Organic Shortbread Cookies", "image": "https://example.com/shortbread-cookies.jpg", "price": 4.49, "details": "Buttery organic shortbread cookies."},
    {"id": 139, "name": "Strawberry Cheesecake", "image": "https://example.com/strawberry-cheesecake.jpg", "price": 6.49, "details": "Creamy cheesecake topped with fresh strawberries."},
    {"id": 140, "name": "Organic Macarons", "image": "https://example.com/organic-macarons.jpg", "price": 7.99, "details": "Delicate organic macarons in assorted flavors."},
    {"id": 141, "name": "Carrot Cake", "image": "https://example.com/carrot-cake.jpg", "price": 5.99, "details": "Moist carrot cake with cream cheese frosting."},
    {"id": 142, "name": "Blueberry Muffins", "image": "https://example.com/blueberry-muffins.jpg", "price": 4.49, "details": "Fresh blueberry muffins with a crumbly top."},
    {"id": 143, "name": "Vanilla Cupcakes", "image": "https://example.com/vanilla-cupcakes.jpg", "price": 3.99, "details": "Soft vanilla cupcakes with buttercream frosting."},
    {"id": 144, "name": "Organic Brownies", "image": "https://example.com/organic-brownies.jpg", "price": 5.49, "details": "Rich organic brownies with a fudgy texture."},
    {"id": 145, "name": "Peach Cobbler", "image": "https://example.com/peach-cobbler.jpg", "price": 6.49, "details": "Sweet peach cobbler with a buttery topping."},
    {"id": 146, "name": "Organic Banana Bread", "image": "https://example.com/banana-bread.jpg", "price": 4.49, "details": "Moist organic banana bread with a hint of spice."},
    {"id": 147, "name": "Chocolate Chip Cookies", "image": "https://example.com/chocolate-chip-cookies.jpg", "price": 3.99, "details": "Classic chocolate chip cookies with a chewy center."},
    {"id": 148, "name": "Raspberry Lemon Bars", "image": "https://example.com/raspberry-lemon-bars.jpg", "price": 4.79, "details": "Tangy raspberry lemon bars with a buttery crust."},
    {"id": 149, "name": "Organic Almond Cake", "image": "https://example.com/almond-cake.jpg", "price": 6.49, "details": "Delicious organic almond cake with a nutty flavor."},
    {"id": 150, "name": "Pumpkin Spice Muffins", "image": "https://example.com/pumpkin-spice-muffins.jpg", "price": 4.99, "details": "Spiced pumpkin muffins perfect for autumn."},
    {"id": 151, "name": "Organic Shampoo", "image": "https://example.com/organic-shampoo.jpg", "price": 8.99, "details": "Gentle organic shampoo for all hair types."},
    {"id": 152, "name": "Natural Toothpaste", "image": "https://example.com/natural-toothpaste.jpg", "price": 4.49, "details": "Fluoride-free natural toothpaste with essential oils."},
    {"id": 153, "name": "Moisturizing Lotion", "image": "https://example.com/moisturizing-lotion.jpg", "price": 6.99, "details": "Rich moisturizing lotion for soft and hydrated skin."},
    {"id": 154, "name": "Organic Facial Cleanser", "image": "https://example.com/facial-cleanser.jpg", "price": 7.49, "details": "Gentle organic facial cleanser for daily use."},
    {"id": 155, "name": "Herbal Deodorant", "image": "https://example.com/herbal-deodorant.jpg", "price": 5.99, "details": "Natural herbal deodorant with no aluminum."},
    {"id": 156, "name": "Lip Balm", "image": "https://example.com/lip-balm.jpg", "price": 2.99, "details": "Moisturizing lip balm with natural flavors."},
    {"id": 157, "name": "Body Scrub", "image": "https://example.com/body-scrub.jpg", "price": 9.49, "details": "Exfoliating body scrub with natural exfoliants."},
    {"id": 158, "name": "Sunscreen SPF 30", "image": "https://example.com/sunscreen.jpg", "price": 12.99, "details": "Broad-spectrum sunscreen with SPF 30 protection."},
    {"id": 159, "name": "Organic Body Wash", "image": "https://example.com/body-wash.jpg", "price": 8.49, "details": "Organic body wash with essential oils."},
    {"id": 160, "name": "Hair Conditioner", "image": "https://example.com/hair-conditioner.jpg", "price": 7.99, "details": "Nourishing hair conditioner for smooth and shiny hair."},
    {"id": 161, "name": "Hand Cream", "image": "https://example.com/hand-cream.jpg", "price": 5.49, "details": "Rich hand cream for dry and cracked hands."},
    {"id": 162, "name": "Shaving Cream", "image": "https://example.com/shaving-cream.jpg", "price": 4.99, "details": "Lathering shaving cream for a smooth shave."},
    {"id": 163, "name": "Organic Face Mask", "image": "https://example.com/face-mask.jpg", "price": 9.99, "details": "Detoxifying organic face mask for all skin types."},
    {"id": 164, "name": "Eye Cream", "image": "https://example.com/eye-cream.jpg", "price": 10.49, "details": "Hydrating eye cream for reducing dark circles."},
    {"id": 165, "name": "Body Oil", "image": "https://example.com/body-oil.jpg", "price": 11.99, "details": "Luxurious body oil for deep hydration."},
    {"id": 166, "name": "Organic Hand Soap", "image": "https://example.com/hand-soap.jpg", "price": 4.99, "details": "Gentle organic hand soap with natural scents."},
    {"id": 167, "name": "Nail Polish", "image": "https://example.com/nail-polish.jpg", "price": 6.99, "details": "Vibrant nail polish in various shades."},
    {"id": 168, "name": "Face Sunscreen SPF 50", "image": "https://example.com/face-sunscreen.jpg", "price": 14.99, "details": "High SPF face sunscreen with anti-aging properties."},
    {"id": 169, "name": "Organic Lip Scrub", "image": "https://example.com/lip-scrub.jpg", "price": 3.99, "details": "Exfoliating lip scrub with natural ingredients."},
    {"id": 170, "name": "Eye Makeup Remover", "image": "https://example.com/eye-makeup-remover.jpg", "price": 5.99, "details": "Gentle eye makeup remover for sensitive skin."},
    {"id": 171, "name": "Organic Hair Oil", "image": "https://example.com/hair-oil.jpg", "price": 8.99, "details": "Nourishing hair oil for damaged hair."},
    {"id": 172, "name": "Anti-Aging Serum", "image": "https://example.com/anti-aging-serum.jpg", "price": 15.49, "details": "Serum with anti-aging properties for youthful skin."},
    {"id": 173, "name": "Organic Bath Salts", "image": "https://example.com/bath-salts.jpg", "price": 7.49, "details": "Relaxing bath salts with essential oils."},
    {"id": 174, "name": "Facial Toner", "image": "https://example.com/facial-toner.jpg", "price": 6.49, "details": "Refreshing facial toner to balance skin pH."},
    {"id": 175, "name": "Foot Cream", "image": "https://example.com/foot-cream.jpg", "price": 5.99, "details": "Moisturizing foot cream for soft and smooth feet."},
    {"id": 176, "name": "Body Butter", "image": "https://example.com/body-butter.jpg", "price": 9.99, "details": "Rich body butter for deep hydration."},
    {"id": 177, "name": "Organic Face Serum", "image": "https://example.com/face-serum.jpg", "price": 12.49, "details": "Hydrating face serum with organic ingredients."},
    {"id": 178, "name": "Beard Oil", "image": "https://example.com/beard-oil.jpg", "price": 7.99, "details": "Nourishing beard oil for soft and manageable facial hair."},
    {"id": 179, "name": "Organic Lip Balm", "image": "https://example.com/organic-lip-balm.jpg", "price": 3.49, "details": "Organic lip balm with natural moisturizers."},
    {"id": 180, "name": "Organic Hair Mask", "image": "https://example.com/hair-mask.jpg", "price": 10.99, "details": "Deep conditioning organic hair mask."},
    {"id": 181, "name": "Eco-Friendly All-Purpose Cleaner", "image": "https://example.com/all-purpose-cleaner.jpg", "price": 6.49, "details": "Natural all-purpose cleaner for various surfaces."},
    {"id": 182, "name": "Disinfectant Wipes", "image": "https://example.com/disinfectant-wipes.jpg", "price": 4.99, "details": "Disinfectant wipes for quick clean-ups."},
    {"id": 183, "name": "Organic Glass Cleaner", "image": "https://example.com/glass-cleaner.jpg", "price": 5.49, "details": "Streak-free organic glass cleaner."},
    {"id": 184, "name": "Baking Soda", "image": "https://example.com/baking-soda.jpg", "price": 2.99, "details": "Multipurpose baking soda for cleaning and deodorizing."},
    {"id": 185, "name": "Natural Floor Cleaner", "image": "https://example.com/floor-cleaner.jpg", "price": 7.99, "details": "Natural floor cleaner safe for all types of flooring."},
    {"id": 186, "name": "Organic Laundry Detergent", "image": "https://example.com/laundry-detergent.jpg", "price": 8.99, "details": "Gentle organic laundry detergent for sensitive skin."},
    {"id": 187, "name": "Microfiber Cleaning Cloths", "image": "https://example.com/microfiber-cloths.jpg", "price": 6.99, "details": "Absorbent microfiber cloths for effective cleaning."},
    {"id": 188, "name": "Natural Dish Soap", "image": "https://example.com/dish-soap.jpg", "price": 3.99, "details": "Eco-friendly dish soap for grease-cutting power."},
    {"id": 189, "name": "Toilet Bowl Cleaner", "image": "https://example.com/toilet-cleaner.jpg", "price": 4.49, "details": "Effective toilet bowl cleaner with a fresh scent."},
    {"id": 190, "name": "Organic Air Freshener", "image": "https://example.com/air-freshener.jpg", "price": 5.49, "details": "Natural air freshener with essential oils."},
    {"id": 191, "name": "Heavy-Duty Sponges", "image": "https://example.com/sponges.jpg", "price": 3.49, "details": "Durable sponges for tough cleaning jobs."},
    {"id": 192, "name": "Organic Fabric Softener", "image": "https://example.com/fabric-softener.jpg", "price": 7.49, "details": "Softens clothes with natural ingredients."},
    {"id": 193, "name": "Cleaning Vinegar", "image": "https://example.com/cleaning-vinegar.jpg", "price": 3.99, "details": "Multipurpose cleaning vinegar for home use."},
    {"id": 194, "name": "Eco-Friendly Trash Bags", "image": "https://example.com/trash-bags.jpg", "price": 6.99, "details": "Biodegradable trash bags for environmentally conscious disposal."},
    {"id": 195, "name": "Organic Carpet Cleaner", "image": "https://example.com/carpet-cleaner.jpg", "price": 8.99, "details": "Effective carpet cleaner with organic ingredients."},
    {"id": 196, "name": "Dishwasher Detergent Tablets", "image": "https://example.com/dishwasher-tablets.jpg", "price": 9.49, "details": "Powerful detergent tablets for dishwashers."},
    {"id": 197, "name": "Natural Oven Cleaner", "image": "https://example.com/oven-cleaner.jpg", "price": 7.99, "details": "Natural cleaner for ovens and grills."},
    {"id": 198, "name": "Scrubbing Brushes", "image": "https://example.com/scrubbing-brushes.jpg", "price": 5.49, "details": "Durable brushes for scrubbing tough stains."},
    {"id": 199, "name": "Organic Dish Soap", "image": "https://example.com/organic-dish-soap.jpg", "price": 4.49, "details": "Gentle organic dish soap with natural ingredients."},
    {"id": 200, "name": "Floor Mop", "image": "https://example.com/floor-mop.jpg", "price": 12.99, "details": "Effective mop for cleaning hard floors."},
    {"id": 201, "name": "Laundry Stain Remover", "image": "https://example.com/laundry-stain-remover.jpg", "price": 5.99, "details": "Natural stain remover for laundry."},
    {"id": 202, "name": "Dishwashing Liquid", "image": "https://example.com/dishwashing-liquid.jpg", "price": 3.99, "details": "Effective liquid dish soap for manual washing."},
    {"id": 203, "name": "Organic Window Cleaner", "image": "https://example.com/window-cleaner.jpg", "price": 6.49, "details": "Streak-free organic window cleaner."},
    {"id": 204, "name": "Heavy-Duty Cleaning Gloves", "image": "https://example.com/cleaning-gloves.jpg", "price": 4.99, "details": "Durable gloves for cleaning tasks."},
    {"id": 205, "name": "Kitchen Cleaner", "image": "https://example.com/kitchen-cleaner.jpg", "price": 5.49, "details": "Natural cleaner for kitchen surfaces."},
    {"id": 206, "name": "Eco-Friendly Sponges", "image": "https://example.com/eco-friendly-sponges.jpg", "price": 4.99, "details": "Biodegradable sponges for environmentally friendly cleaning."},
    {"id": 207, "name": "Organic Furniture Polish", "image": "https://example.com/furniture-polish.jpg", "price": 7.49, "details": "Natural polish for wood and furniture."},
    {"id": 208, "name": "Glass Cleaning Wipes", "image": "https://example.com/glass-cleaning-wipes.jpg", "price": 5.49, "details": "Wipes specifically for cleaning glass surfaces."},
    {"id": 209, "name": "Natural Carpet Freshener", "image": "https://example.com/carpet-freshener.jpg", "price": 6.99, "details": "Organic freshener for carpets and rugs."},
    {"id": 210, "name": "Wood Cleaner", "image": "https://example.com/wood-cleaner.jpg", "price": 8.49, "details": "Effective cleaner for wood surfaces."},
    {"id": 211, "name": "Electric Kettle", "image": "https://example.com/electric-kettle.jpg", "price": 29.99, "details": "Fast-boiling electric kettle with auto shut-off."},
    {"id": 212, "name": "Blender", "image": "https://example.com/blender.jpg", "price": 49.99, "details": "High-speed blender with multiple settings."},
    {"id": 213, "name": "Food Processor", "image": "https://example.com/food-processor.jpg", "price": 89.99, "details": "Versatile food processor with various attachments."},
    {"id": 214, "name": "Coffee Maker", "image": "https://example.com/coffee-maker.jpg", "price": 39.99, "details": "Programmable coffee maker with a built-in grinder."},
    {"id": 215, "name": "Toaster", "image": "https://example.com/toaster.jpg", "price": 24.99, "details": "Four-slot toaster with adjustable browning control."},
    {"id": 216, "name": "Electric Can Opener", "image": "https://example.com/can-opener.jpg", "price": 15.99, "details": "Automatic can opener for easy use."},
    {"id": 217, "name": "Slow Cooker", "image": "https://example.com/slow-cooker.jpg", "price": 39.99, "details": "Programmable slow cooker with multiple heat settings."},
    {"id": 218, "name": "Instant Pot", "image": "https://example.com/instant-pot.jpg", "price": 99.99, "details": "Multi-functional pressure cooker with various modes."},
    {"id": 219, "name": "Air Fryer", "image": "https://example.com/air-fryer.jpg", "price": 79.99, "details": "Compact air fryer for healthier cooking."},
    {"id": 220, "name": "Stand Mixer", "image": "https://example.com/stand-mixer.jpg", "price": 129.99, "details": "Powerful stand mixer with multiple attachments."},
    {"id": 221, "name": "Rice Cooker", "image": "https://example.com/rice-cooker.jpg", "price": 34.99, "details": "Easy-to-use rice cooker with keep-warm function."},
    {"id": 222, "name": "Electric Griddle", "image": "https://example.com/electric-griddle.jpg", "price": 44.99, "details": "Large electric griddle with adjustable temperature control."},
    {"id": 223, "name": "Digital Meat Thermometer", "image": "https://example.com/meat-thermometer.jpg", "price": 18.99, "details": "Instant-read digital meat thermometer for perfect cooking."},
    {"id": 224, "name": "Mandoline Slicer", "image": "https://example.com/mandoline-slicer.jpg", "price": 22.99, "details": "Adjustable mandoline slicer for precise cuts."},
    {"id": 225, "name": "Immersion Blender", "image": "https://example.com/immersion-blender.jpg", "price": 29.99, "details": "Handheld immersion blender for soups and sauces."},
    {"id": 226, "name": "Electric Peeler", "image": "https://example.com/electric-peeler.jpg", "price": 25.99, "details": "Automatic peeler for fruits and vegetables."},
    {"id": 227, "name": "Popcorn Maker", "image": "https://example.com/popcorn-maker.jpg", "price": 19.99, "details": "Easy-to-use popcorn maker for fresh popcorn."},
    {"id": 228, "name": "Cheese Grater", "image": "https://example.com/cheese-grater.jpg", "price": 9.99, "details": "Multi-side cheese grater for various grating needs."},
    {"id": 229, "name": "Food Scale", "image": "https://example.com/food-scale.jpg", "price": 14.99, "details": "Digital food scale for accurate measurements."},
    {"id": 230, "name": "Tea Infuser", "image": "https://example.com/tea-infuser.jpg", "price": 6.99, "details": "Stainless steel tea infuser for loose leaf tea."},
    {"id": 231, "name": "Pasta Maker", "image": "https://example.com/pasta-maker.jpg", "price": 69.99, "details": "Manual pasta maker for fresh homemade pasta."},
    {"id": 232, "name": "Egg Cooker", "image": "https://example.com/egg-cooker.jpg", "price": 17.99, "details": "Electric egg cooker for perfect eggs."},
    {"id": 233, "name": "Wine Opener", "image": "https://example.com/wine-opener.jpg", "price": 12.99, "details": "Electric wine opener for easy bottle opening."},
    {"id": 234, "name": "Salad Spinner", "image": "https://example.com/salad-spinner.jpg", "price": 8.99, "details": "Salad spinner for quick and easy drying of greens."},
    {"id": 235, "name": "Bread Maker", "image": "https://example.com/bread-maker.jpg", "price": 89.99, "details": "Automatic bread maker with various baking options."},
    {"id": 236, "name": "Crepe Maker", "image": "https://example.com/crepe-maker.jpg", "price": 32.99, "details": "Electric crepe maker for perfect crepes."},
    {"id": 237, "name": "Spice Grinder", "image": "https://example.com/spice-grinder.jpg", "price": 19.99, "details": "Electric spice grinder for fresh ground spices."},
    {"id": 238, "name": "French Press", "image": "https://example.com/french-press.jpg", "price": 14.99, "details": "Classic French press for brewing coffee."},
    {"id": 239, "name": "Ice Cream Maker", "image": "https://example.com/ice-cream-maker.jpg", "price": 79.99, "details": "Electric ice cream maker for homemade treats."},
    {"id": 240, "name": "Countertop Blender", "image": "https://example.com/countertop-blender.jpg", "price": 49.99, "details": "Durable countertop blender for smoothies and more."},
    {"id": 241, "name": "Smartphone", "image": "https://example.com/smartphone.jpg", "price": 699.99, "details": "Latest model smartphone with advanced features."},
    {"id": 242, "name": "Laptop", "image": "https://example.com/laptop.jpg", "price": 999.99, "details": "High-performance laptop with a fast processor."},
    {"id": 243, "name": "Bluetooth Headphones", "image": "https://example.com/bluetooth-headphones.jpg", "price": 149.99, "details": "Wireless Bluetooth headphones with noise-canceling."},
    {"id": 244, "name": "Smartwatch", "image": "https://example.com/smartwatch.jpg", "price": 199.99, "details": "Feature-packed smartwatch with health tracking."},
    {"id": 245, "name": "Digital Camera", "image": "https://example.com/digital-camera.jpg", "price": 499.99, "details": "High-resolution digital camera with multiple modes."},
    {"id": 246, "name": "Tablet", "image": "https://example.com/tablet.jpg", "price": 399.99, "details": "Versatile tablet with a high-resolution screen."},
    {"id": 247, "name": "Portable Charger", "image": "https://example.com/portable-charger.jpg", "price": 29.99, "details": "Compact portable charger for charging on the go."},
    {"id": 248, "name": "Smart TV", "image": "https://example.com/smart-tv.jpg", "price": 799.99, "details": "4K Smart TV with streaming capabilities."},
    {"id": 249, "name": "Bluetooth Speaker", "image": "https://example.com/bluetooth-speaker.jpg", "price": 99.99, "details": "Wireless Bluetooth speaker with high sound quality."},
    {"id": 250, "name": "External Hard Drive", "image": "https://example.com/external-hard-drive.jpg", "price": 119.99, "details": "High-capacity external hard drive for data storage."},
    {"id": 251, "name": "Home Security Camera", "image": "https://example.com/security-camera.jpg", "price": 149.99, "details": "Smart security camera with motion detection."},
    {"id": 252, "name": "Wireless Mouse", "image": "https://example.com/wireless-mouse.jpg", "price": 24.99, "details": "Ergonomic wireless mouse with adjustable DPI."},
    {"id": 253, "name": "Keyboard", "image": "https://example.com/keyboard.jpg", "price": 49.99, "details": "Mechanical keyboard with backlighting."},
    {"id": 254, "name": "Smart Home Hub", "image": "https://example.com/home-hub.jpg", "price": 79.99, "details": "Central hub for controlling smart home devices."},
    {"id": 255, "name": "Gaming Console", "image": "https://example.com/gaming-console.jpg", "price": 399.99, "details": "Latest gaming console with 4K resolution."},
    {"id": 256, "name": "4K Monitor", "image": "https://example.com/4k-monitor.jpg", "price": 299.99, "details": "Ultra-high-definition 4K monitor."},
    {"id": 257, "name": "Action Camera", "image": "https://example.com/action-camera.jpg", "price": 249.99, "details": "Durable action camera for capturing adventures."},
    {"id": 258, "name": "Smart Thermostat", "image": "https://example.com/smart-thermostat.jpg", "price": 149.99, "details": "Programmable thermostat with Wi-Fi connectivity."},
    {"id": 259, "name": "Fitness Tracker", "image": "https://example.com/fitness-tracker.jpg", "price": 99.99, "details": "Wearable fitness tracker with activity monitoring."},
    {"id": 260, "name": "Digital Thermometer", "image": "https://example.com/digital-thermometer.jpg", "price": 19.99, "details": "Instant-read digital thermometer for accurate measurements."},
    {"id": 261, "name": "Wireless Router", "image": "https://example.com/wireless-router.jpg", "price": 89.99, "details": "High-speed wireless router with advanced features."},
    {"id": 262, "name": "E-Reader", "image": "https://example.com/e-reader.jpg", "price": 129.99, "details": "E-reader with a high-resolution display and adjustable backlight."},
    {"id": 263, "name": "Smart Plug", "image": "https://example.com/smart-plug.jpg", "price": 24.99, "details": "Wi-Fi enabled smart plug for controlling devices remotely."},
    {"id": 264, "name": "Portable Speaker", "image": "https://example.com/portable-speaker.jpg", "price": 79.99, "details": "Compact portable speaker with robust sound quality."},
    {"id": 265, "name": "Smart Light Bulbs", "image": "https://example.com/smart-light-bulbs.jpg", "price": 39.99, "details": "Color-changing smart light bulbs with remote control."},
    {"id": 266, "name": "Digital Picture Frame", "image": "https://example.com/digital-picture-frame.jpg", "price": 89.99, "details": "Digital picture frame with high-resolution display."},
    {"id": 267, "name": "Laptop Stand", "image": "https://example.com/laptop-stand.jpg", "price": 29.99, "details": "Adjustable laptop stand for ergonomic use."},
    {"id": 268, "name": "Portable Air Conditioner", "image": "https://example.com/portable-air-conditioner.jpg", "price": 399.99, "details": "Portable air conditioner with adjustable settings."},
    {"id": 269, "name": "Electric Toothbrush", "image": "https://example.com/electric-toothbrush.jpg", "price": 79.99, "details": "Rechargeable electric toothbrush with multiple modes."},
    {"id": 270, "name": "Cordless Vacuum Cleaner", "image": "https://example.com/cordless-vacuum.jpg", "price": 199.99, "details": "Cordless vacuum cleaner."}
]



export default AllProducts;